# PostgreSQL only
connectionString: jdbc:postgresql://localhost:5432/benchbase?user=postgres&password=postgres
# table that stores the transactions' results
# schema (table_name varchar, column_name varchar, pk varchar, commit int, aborts int, last_updated timestamp)
# primary key (table_name, column_name, pk)
statusTable: tx_status
# number of workers to adjust the number of nodes (0 to disable)
adjustWorkers: 0
# time between adjusts (ms)
adjustDelta: 200
# only adjust if the MRV was modified between now() - adjustDelta * adjustWindow / 100 and now()
adjustWindow: 25 # adjust only if the record was updated percentage of adjustDelta
# starts decreasing the number of nodes if MRV value / current nodes < minAverageAmountPerNode
minAverageAmountPerNode: 1
# maximum number of nodes per MRV allowed
maxNodes: 1024
# minimum number of nodes per MRV allowed
minNodes: 1
# abort rate goal the adjust worker should aim to
arGoal: 0.05
# abort rate below which the adjust worker starts removing nodes
arMin: 0.01
# measures the number of nodes per mrv
monitor: false
# time between monitor measuring
monitorDelta: 200 #ms
# tables to monitor
monitorTables:
  - tb_name
# refreshes counter values
refresh: true
# time between counter refresh
refreshDelta: 100 #ms
# tables to refresh
refreshTables:
  - tb_name
